python train.py \
    --coco_root /path/to/coco \
    --lut_dir /path/to/luts \
    --pretrained_path /path/to/efficientnet_b0.pth \
    --ckpt_dir /path/to/checkpoints \
    --epochs 100 \
    --batch_size 24 \
    --lr 3e-4 \
    --lr_step_size 24 \
    --lr_gamma 0.1 \
    --image_size 256 \
    --device cuda
